class Node(object):
    """Nodes represents discrete random variables.
    """
    
    def __init__(self, name, ls_parents=[]):
        self.name = name
        self.ls_parents = ls_parents
        self.cpt = None  # to be generated by BN

    def get_parents(self):
        return self.ls_parents
        
    @property
    def is_marginal(self):
        """a marginal node does not have any parents."""
        return not self.ls_parents